// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBNaDyy5frRHfNfLAU41tROjp-BVvn75hg',
    appId: '1:688828851515:web:76a9f2ba92540adde6c31e',
    messagingSenderId: '688828851515',
    projectId: 'rtdatabase-1a3ce',
    authDomain: 'rtdatabase-1a3ce.firebaseapp.com',
    storageBucket: 'rtdatabase-1a3ce.appspot.com',
    measurementId: 'G-5FRMJM5S6J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQ543BkSKhXV3bdsQZvM7AsbkVbkDUKQY',
    appId: '1:688828851515:android:62179d0fce12550ae6c31e',
    messagingSenderId: '688828851515',
    projectId: 'rtdatabase-1a3ce',
    storageBucket: 'rtdatabase-1a3ce.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBNaDyy5frRHfNfLAU41tROjp-BVvn75hg',
    appId: '1:688828851515:web:7289573c4b4cb62fe6c31e',
    messagingSenderId: '688828851515',
    projectId: 'rtdatabase-1a3ce',
    authDomain: 'rtdatabase-1a3ce.firebaseapp.com',
    storageBucket: 'rtdatabase-1a3ce.appspot.com',
    measurementId: 'G-T0KDS4G4PW',
  );
}
